import Container from '@/components/FrontendLayout/Container';
import Todo from '@/components/Todo/Todo';
import FrontendLayout from '@layouts/FrontendLayout';
import Head from 'next/head';
export default function todo() {
    return (
        <FrontendLayout>
            <Head>
                <title>App | Next Todo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <Todo />
            </Container>
        </FrontendLayout>
    );
}
